@startuml
class Tablero {
    + DIMENSION: int
    + estadoActual: int[][]
    + estadoSiguiente: int[][]
    --
    + leerEstadoActual(): void
    + generarEstadoActualPorMontecarlo(): void
    + transitarAlEstadoSiguiente(): void
    + toString(): String
}

class Principal {
    + main(String[] args): void
}

Principal --> Tablero : usa

@enduml